json:
  logger.application.name: "common-apps"
  logger.application.version: "1.0"
retry:
  count:  "3"
  interval: "3000"
  
APIKIT_BAD_REQUEST: "Bad Request Received. Please check the request"
APIKIT_METHOD_NOT_ALLOWED: "Method Not Allowed"
APIKIT_NOT_ACCEPTABLE: "Request Not Acceptable"
APIKIT_NOT_FOUND: "Resource Not Found"
APIKIT_UNSUPPORTED_MEDIA_TYPE: "Unsupported Media Type. Please check the media type"
HTTP_BAD_REQUEST: "Bad Request"
HTTP_CLIENT_SECURITY: "Security Error"
HTTP_CONNECTIVITY: "Connectivity Error Occurred"
HTTP_FORBIDDEN: "Forbidden Error Occurred"
HTTP_INTERNAL_SERVER_ERROR: "Internal Server Error"
HTTP_METHOD_NOT_ALLOWED: "Method Not Allowed"
HTTP_NOT_ACCEPTABLE: "Not Acceptable"
HTTP_NOT_FOUND: "Resource Not Found"
HTTP_PARSING: "Parsing Error"
HTTP_RETRY_EXHAUSTED: "Retry Exhausted"
HTTP_SECURITY: "Security Error"
HTTP_TIMEOUT: "Timeout error occurred while calling the system"
HTTP_TOO_MANY_REQUESTS: "Too many requests received"
HTTP_UNAUTHORIZED: "Unauthorized"
HTTP_UNSUPPORTED_MEDIA_TYPE: "Unsupported Media Type"
RETRY_EXHAUSTED: "Not able to connect to end system"
REDELIVERY_EXHAUSTED: "Redelivery Exhausted. Please try again"
TRANSFORMATION: " Transformation Error Occurred"
EXPRESSION: "Expression Error Occurred"
ROUTING: "Routing Error Occurred"
SALESFORCE_INVALID_INPUT: "Invalid Input Received"
INTERNAL_SERVER_ERROR: "Internal Server Error"