#%RAML 1.0 Trait
responses:
  400:
    description: The server cannot or will not process the request due to something that is perceived to be a client error.
    body:
      application/json:
        type: !include ../types/common/common-error-response.raml
        example: |
          { 
            "errorCode": "400",
            "correlationId": "6d5d83d0-2df4-11ef-9971-02a584aeafd9",
            "errorType": "HTTP:BAD_REQUEST",
            "errorMessage": "The request could not be understood by the server due to invalid",
            "timestamp": "2020-06-15T15:13:10",
            "additionalDetails": "add additional error details here ..."
            }   
  401:
    description: No valid credentials found to access the requested resource
    body:
      application/json:
        type: !include ../types/common/common-error-response.raml
        example: |
          {
              "errorCode": "401",
              "correlationId": "6d5d83d0-2df4-11ef-9971-02a584aeafd9",
              "errorType": "UNAUTHORIZED",
              "errorMessage": "Required credentials are missing or invalid.",
              "timestamp": "2020-06-15T15:13:10",
              "additionalDetails": "add additional error details here ..."
          }
  403:
    description: The server has refused access to the requested resource
    body:
      application/json:
        type: !include ../types/common/common-error-response.raml
        example: |
          {
            "errorCode": "403",
            "correlationId": "6e560258-4e55-4839-b7d9-29c80f12263d",
            "errorType": "FORBIDDEN",
            "errorMessage": "Access to the requested resource was denied",
            "timestamp": "2020-06-15T15:13:10",
            "additionalDetails": "add additional error details here ..."
          }
  404:
    description: The server cannot find the requested resource
    body:
      application/json:
        type: !include ../types/common/common-error-response.raml
        example: |
          {
            "errorCode": "404",
            "correlationId": "6e560258-4e55-4839-b7d9-29c80f12263d",
            "errorType": "NOT_FOUND",
            "errorMessage": "Requested resource was not found",
            "timestamp": "2020-06-15T15:13:10",
            "additionalDetails": "add additional error details here ..."
          }
  405:
    description: The request method is not supported for the requested resource
    body:
      application/json:
        type: !include ../types/common/common-error-response.raml
        example: |
          {
            "errorCode": "405",
            "correlationId": "6e560258-4e55-4839-b7d9-29c80f12263d",
            "errorType": "METHOD_NOT_ALLOWED",
            "errorMessage": "The target resource does not support the requested method",
            "timestamp": "2020-06-15T15:13:10",
            "additionalDetails": "add additional error details here ..."
          }
  406:
    description: The target resource does not have a current representation that would be acceptable to the user agent
    body:
      application/json:
        type: !include ../types/common/common-error-response.raml
        example: |
          {
            "errorCode": "406",
            "correlationId": "6e560258-4e55-4839-b7d9-29c80f12263d",
            "errorType": "NOT_ACCEPTABLE",
            "errorMessage": "The requested resource cannot provide acceptable content",
            "timestamp": "2020-06-15T15:13:10",
            "additionalDetails": "add additional error details here ..."
          }
  415:
    description: The accept header specified an unsupported media type.
    body:
      application/json:
        type: !include ../types/common/common-error-response.raml
        example: |
          {
            "errorCode": "415",
            "correlationId": "6e560258-4e55-4839-b7d9-29c80f12263d",
            "errorType": "UNSUPPORTED_MEDIA_TYPE",
            "errorMessage": "The server is refusing the request because it is not in a format supported by the resource",
            "timestamp": "2020-06-15T15:13:10",
            "additionalDetails": "add additional error details here ..."
          }
  429:
    description: An API request rate limit has been exceeded.
    body:
      application/json:
        type: !include ../types/common/common-error-response.raml
        example: |
          {
            "errorCode": "429",
            "correlationId": "6e560258-4e55-4839-b7d9-29c80f12263d",
            "errorType": "TOO_MANY_REQUESTS",
            "errorMessage": "The server is refusing to handle the request because a rate limit has been exceeded",
            "timestamp": "2020-06-15T15:13:10",
            "additionalDetails": "add additional error details here ..."
          }
  500: 
    description: An internal error occurred while processing the API request
    body:
      application/json:
        type: !include ../types/common/common-error-response.raml
        example: |
          {
            "errorCode": "500",
            "correlationId": "6e560258-4e55-4839-b7d9-29c80f12263d",
            "errorType": "INTERNAL_SERVER_ERROR",
            "errorMessage": "The server was unable to process the request due to an internal error",
            "timestamp": "2020-06-15T15:13:10",
            "additionalDetails": "add additional error details here ..."
          }
  501:
    description: The method has not been implemented 
    body:
      application/json:
        type: !include ../types/common/common-error-response.raml
        example: |
          {
            "errorCode": "501",
            "correlationId": "6e560258-4e55-4839-b7d9-29c80f12263d",
            "errorType": "NOT_IMPLEMENTED",
            "errorMessage": "Not Implemented.",
            "timestamp": "2020-06-15T15:13:10",
            "additionalDetails": "add additional error details here ..."
          }
  503: 
    description: The server is Unavailable
    body:
      application/json:
        type: !include ../types/common/common-error-response.raml
        example: |
          {
            "errorCode": "503",
            "correlationId": "6e560258-4e55-4839-b7d9-29c80f12263d",
            "errorType": "SERVICE_UNAVAILABLE",
            "errorMessage": "Service Unavailable.",
            "timestamp": "2020-06-15T15:13:10",
            "additionalDetails": "add additional error details here ..."
          }